env:
  es6: true
  node: true
  jest: true

extends:
  - eslint:recommended
  - plugin:node/recommended

parserOptions:
  ecmaVersion: 2020

rules:
  arrow-spacing: error
  complexity: [ error, 6 ]
  curly: [ error, all ]
  indent: [ error, 2 ]
  key-spacing: [ error, { beforeColon: false } ]
  linebreak-style: [ error, unix ]
  no-console: [ error ]
  no-process-exit: off
  no-trailing-spaces: [ error ]
  quotes: [ error, single ]
  semi: [ error, always ]
  space-infix-ops: [ error ]
  strict: [ error, "global" ]

overrides:

  - files: [ "scripts/**" ]
    rules:
      node/shebang: [ off ]
      no-console: [ off ]
      node/no-unpublished-require: [ off ]

  - files: [ "features/**" ]
    rules:
      no-console: [ off ]
      node/no-unpublished-require: [ off ]
    globals:
      Given: readonly
      When: readonly
      Then: readonly
      Before: readonly
      After: readonly
